services:
    gpslab.date.listener.response:
        class: GpsLab\Bundle\DateBundle\Event\Listener\ResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponseSaveUserTimeZone }
        arguments:
            - '@gpslab.date.tz.keeper'
            - '%date.time_zone.cookie.used%'
            - '%date.time_zone.cookie.param.name%'
            - '%date.time_zone.cookie.param.offset%'
