services:
    gpslab.date.tz.resolver.collection:
        class: GpsLab\Bundle\DateBundle\TimeZone\Resolver\CollectionResolver
        public: false

    gpslab.date.tz.resolver.console:
        class: GpsLab\Bundle\DateBundle\TimeZone\Resolver\ConsoleResolver
        arguments: [ '%date.time_zone%' ]
        tags:
            - { name: gpslab.date.tz.resolver, priority: 1 }
        public: false

    gpslab.date.tz.resolver.request:
        class: GpsLab\Bundle\DateBundle\TimeZone\Resolver\RequestResolver
        arguments:
            - '@request_stack'
            - '%date.time_zone.cookie.used%'
            - '%date.time_zone.cookie.param.name%'
        tags:
            - { name: gpslab.date.tz.resolver, priority: 1000 }
        public: false
